name: Notify Website of Guide Update

on:
  push:
    branches: [release]

jobs:
  notify-website:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger website guide sync
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.WEBSITE_REPO_TOKEN }}
        repository: umanitoba-cssa/cssa-website-next
        event-type: guide-updated
        client-payload: |
          {
            "guide_repo": "${{ github.repository }}",
            "guide_ref": "${{ github.ref }}",
            "guide_sha": "${{ github.sha }}"
          }
