name: Lint Workfow

on:
  workflow_call:
  workflow_dispatch:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --ignore-scripts --frozen-lockfile

      - name: Run ESLint
        run: bun run eslint .

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --ignore-scripts --frozen-lockfile

      - name: Run Prettier check
        run: bun run prettier --check .
